### PR TITLE
No need for early trimming to be a warning

### PR DESCRIPTION
**Pull request by mattsaxon**
I think we've seen enough of this to be sure it's not causing a problem, lets downgrade it to a debug message to clear up our logs

### CODE REVIEW

**Comment by sjeffrey101** [comment]
only thing with this is that no one should really recieve the message apart from at the start.  If this is seen in the log then there is a problem, like its missing serial data.

Happy for you to merge if you want that, but to me i think its a useful message.  It doesnt cause me an issue as im in debug any way, and quite honestly i never experience this message.

**Review by sjeffrey101 — DISMISSED** [review]

**Comment by mattsaxon** [comment]
That's a fair comment, let me rethink, perhaps its a bit more complex to code, but I could look to set a timer and ignore at startup  only

**Comment by sjeffrey101** [comment]
rather than a timer, what about a flag that gets set when the first surccesful message is recieved.  then it sends as a debug when flag is not set and warn when it is set.

**Comment by mattsaxon** [comment]
New commit made to do exactly as  you suggest

**Review by sjeffrey101 — APPROVED** [review]
looks good.

**Pull request merged**
