### PR TITLE
Add Actions to verify against HASFest and Hacs checker

### PR DESCRIPTION
**Pull request by sjeffrey101**
Also update the manifest to pass.

this means that on each pull request it will do some basic checks to make sure it is a valid component and repository.

reqruired to be part of hacs.

https://github.com/home-assistant/actions#hassfest
https://github.com/hacs/action

### CODE REVIEW

**Comment by sjeffrey101** [comment]
also you will need to add some topics to the respository.   i suggest "Speakercraft", "MZC", "Homeassistant"

**Review by mattsaxon — APPROVED** [review]

**Comment by mattsaxon** [comment]
@sjeffrey101 Successful test, I merged this and the HACS action failed, giving the error that I had no topics, which I've now added. When you access the PR ive just raised hopefully this will pass

**Comment by sjeffrey101** [comment]
yep all good.  i've currently set the HACS not to check the home assistant brands - which is where we need to store a speakercraft logo i think.  but eveyrthing else passes.

**Comment by mattsaxon** [comment]
OK, this is their default one https://www.speakercraft.com/wp-content/uploads/2020/12/2020-SpeakerCraft-Logo1.png

Can we just point to that?

**Comment by mattsaxon** [comment]
Although looking at how things render, maybe this one is better https://images.app.goo.gl/RotsrFnCghRkVBq49 or even perhaps the AppStore one https://apps.apple.com/gb/app/speakercraft-app/id910217017

Can we point to it, or must it be hosted with the integration?

**Pull request merged**
